# Generated by Django 5.2.8 on 2025-11-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='Candidate',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='Vote',
        ),
        migrations.AlterModelTable(
            name='voter',
            table='Voter',
        ),
    ]
